version: ‘3.8’

services:
  postgres:
    image: 'postgres:15'
    ports:
      - 5432:5432
    volumes:
      - ./PostgresData:/var/lib/postgresql
      - ./Scripts:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: 'POSTGRES_DB'
      POSTGRES_USER: 'USER'
      POSTGRES_PASSWORD: 'PASS'