version: '3.8'

services:
  postgres:
    container_name: 'DB_Container'
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    volumes:
      - ./PostgresData:/var/lib/postgresql
      - ./Scripts:/docker-entrypoint-initdb.d/
    #entrypoint: bash "/docker-entrypoint-initdb.d/init.sh"
    environment:
      POSTGRES_DB: 'POSTGRES_DB'
      POSTGRES_USER: 'USER'
      POSTGRES_PASSWORD: 'PASS'
      TAXCAR_DB_VERSION: '1.0.0'