version: '3.8'

services:
  postgres:
    container_name: 'DB_Container'
    image: 'postgres:16.0'
    mem_reservation: 5GB
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql
      - ./Common/scripts/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./Common/scripts:/docker-entrypoint-initdb.d/scripts
      - ./Common/initialMigration:/docker-entrypoint-initdb.d/initialMigration
      - ./Common/analization:/docker-entrypoint-initdb.d/analization
      - ./PG_Backup:/docker-entrypoint-initdb.d/PG_Backup
    command: |
      postgres
      -c wal_level=minimal
      -c archive_mode=off
      -c max_wal_senders=0
      -c max_wal_size=10GB
      -c min_wal_size=5GB

    environment:
      POSTGRES_DB: 'POSTGRES_DB'
      POSTGRES_USER: 'USER'
      POSTGRES_PASSWORD: 'PASS'
      TAXCAR_DB_VERSION: '1.0.1'
      BACKUP_COUNT: '5'
      BACKUP_DAY_FREQUENCE: '2'

volumes:
  pg_data: